org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2
minecraft_mappings_channel=stable
minecraft_mappings_version=39-1.12
forge_version=14.23.5.2860
jei_version=4.16.1.302

mod_version=2.9.10+hf3
mod_group=net.mrbt0907.weather2
mod_name=Weather2Remastered-1.12.2
coroutil_jar=coroutil-1.12.1-1.2.37.jar

client_directory=run
server_directory=run (Server)